<?php

namespace AppBundle\Repository;

/**
 * PlanCollectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanCollectionRepository extends \Doctrine\ORM\EntityRepository
{
}
